spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xshssb123
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #空闲连接最大存活时间
      idle-timeout: 180000
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #测试连接是否可用
      connection-test-query: SELECT 1

  redis:
    host: 192.168.68.129
    port: 6380
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    host: 192.168.68.129
    username: root
    password: 123456
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms


mybatis-plus:
  #配置mapper.xml的映射位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.sangjie.seckill.pojo


#打印日志（方法接口所在的包）
logging:
  level:
    com.sangjie.seckill.mapper: debug